name: Publish release
on:
  release:
    types: [published]
jobs:
  publish:
    name: Build, pack & publish - Iggy.Net
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      # Publish
      - name: Build Xena soltion
        run: dotnet build Xena.sln

      - name: Publish NuGet packages to NuGet.org
        run: dotnet nuget push src/**/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
